### ISSUE TITLE
Examples would be nice...

### ISSUE THREAD

**Issue by SebastianApel** [merlin-neurotech/WizardHat#24]
**Is your feature request related to a problem? Please describe.**
I tried to use the project, but failed to do so. The example code in the readme is not enough.

**Describe the solution you'd like**
I'd like to see a couple of examples (ideally plotting raw data in realtime, maybe even fft data of the brainwave bands)

**Comment by oori** [comment]
Basic examples are in the [scripts](https://github.com/merlin-neurotech/WizardHat/tree/master/scripts) folder.
